version: '3.8'

services:
  ls-icons:
    build: .
    volumes:
      - .:/app
      - ${HOME}:/home/user:ro
    working_dir: /app
    environment:
      - TERM=xterm-256color

  test:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: python -m unittest test_ls.py 